namespace DraconiusGoGUI.Enums
{
    public enum LoggerTypes
    {
        Debug,
        Info,
        Warning,
        Exception,
        FatalError,
        CreatureEscape,
        CreatureFlee,
        LocationUpdate,
        Gym,
        Transfer,
        Evolve,
        Incubate,
        Recycle,
        ProxyIssue,
        Success,
        Captcha,
        Deploy,
        Buddy,
        AwardedBadges,
        HatchedEggs,
        Upgrade,
        LevelUp,
        Snipe
    };
}